### ISSUE TITLE
Site branding

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#105]
Please include LIT and Kartoza branding in the footer for all pages:

![image](https://user-images.githubusercontent.com/178003/125597945-2b8cddea-8d8a-43c7-b49a-99ce2f9fb4cb.png)

@Andrevdb can you provide some monochrome branding for the space in the footer.

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/128150861-c55109b9-72ae-450c-b6f3-468cc5dbd168.png)

![KartozaLogoHorizontalDarkBackgroundCMYK](https://user-images.githubusercontent.com/178003/128151227-5d9cbe1e-bdb8-42d6-a40d-0cfc8f8e9373.png)

**Comment by timlinux** [comment]
Powered by open source can link to the github project

**Comment by Andrevdb** [comment]
![northarrow_bc](https://user-images.githubusercontent.com/40511773/128209540-c740cee3-e398-4eeb-980f-9487d05513d3.png)
Here's a new logo that we'll be using for LandInfo
