### ISSUE TITLE
Onboarding page organisation

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#106]
![image](https://user-images.githubusercontent.com/178003/125599333-d8fd7c69-074d-463a-9900-6eb8ac6b6cc3.png)

**Comment by timlinux** [comment]
Also can we remove the colons throughout the site after the field names

**Comment by meomancer** [comment]
This is implemented @timlinux 
![Selection_353](https://user-images.githubusercontent.com/4530905/125904304-dedb37cf-eb02-4f05-877d-f7126d850f20.png)

please review it
currently i don't drop the organisation name, instead user can let it empty to name it same with comunity
