### ISSUE TITLE
Org management form tweak

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#108]
![image](https://user-images.githubusercontent.com/178003/125601031-a14d0d08-0c19-451d-8be4-88ccb60b236a.png)

Add teh community column for each org

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/125601117-54b70b92-f823-404f-abb8-c4759a599430.png)

Capital O please

**Comment by meomancer** [comment]
This is fixed
![Selection_357](https://user-images.githubusercontent.com/4530905/125904975-548a6be9-43a8-4077-9e24-02afa676e72e.png)
