### ISSUE TITLE
Organisation management

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#109]
![image](https://user-images.githubusercontent.com/178003/125601282-91c4eee3-f350-437c-9273-b3feb7886c8d.png)

- [x] Open Community Map

- [x] Subscribe to be able to give user access to the organisation. Subscriptions

- [x] Subscribe to manage users for your organisation. [Subscribe]

- [x] Make the subscribe a pill button

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/125602106-abec2d30-5c4e-48b2-8d74-4328c78e7c99.png)

Can get rid of profile I think

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/125602335-a8b02c72-6edb-40a4-9b79-d12ccdcdb28f.png)

Invite User

**Comment by meomancer** [comment]
This is fixed
