### ISSUE TITLE
Constistency of terms for login vs sign in

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#128]
Sign in feels more friendly right?

![image](https://user-images.githubusercontent.com/178003/128148886-1735f6f0-103f-4ea6-804f-844a39bf8f8f.png)

![image](https://user-images.githubusercontent.com/178003/128148997-7c55ebb6-1f34-4035-b690-781164188635.png)

**Comment by meomancer** [comment]
This is fixed
