### ISSUE TITLE
Chunky boxes

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#130]
I really like the chunky box design approach for making users feel confident when using the site

![image](https://user-images.githubusercontent.com/178003/128149945-c63f3683-116f-4410-98c1-454ed1a2499f.png)

Can we do this where forms are simple e,g, login and signup pages and elsewhere where possible....

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/128150059-0a3fd860-a51c-4e3f-a084-47bb3a46aadb.png)

**Comment by meomancer** [comment]
This is updated
