### ISSUE TITLE
Maintenance -> renewal

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#135]
![image](https://user-images.githubusercontent.com/178003/128731991-d7cc5613-e882-4ffc-b818-eb4a5e355957.png)

**Comment by meomancer** [comment]
hi @Andrevdb 
The API return renewal_cost and maintenance_cost
Which one should i use?
Maintenance cost or Renewal Cost?
Or should we merge it or split it?

**Comment by Andrevdb** [comment]
Hi @meomancer  Let's only show renewal cost for now
