### ISSUE TITLE
We need to show risk values grouped by subclasses

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#136]
![image](https://user-images.githubusercontent.com/178003/128732111-1630acc4-7ac7-4a0e-8df6-2261743a3fb6.png)

@Andrevdb to provide details please

**Comment by Andrevdb** [comment]
https://docs.google.com/spreadsheets/d/1l9Ll8E9tiQlqQRvBGOWsRyv6cvJVVb32yDFmvYx2qe0/edit#gid=2110259830

**Comment by meomancer** [comment]
Create that maintenance cost by sub classes to also classify based on probability of failure
![Selection_006](https://user-images.githubusercontent.com/4530905/128733103-3c485874-27d3-47be-a829-ff26b4c4572d.png)
