### ISSUE TITLE
Download chart data

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#137]
![image](https://user-images.githubusercontent.com/178003/128733135-3c234b28-1b26-4588-a9b0-bae75b20b482.png)
 

![image](https://user-images.githubusercontent.com/178003/128733205-6a11e92e-d000-4428-aeb4-7879dcc68b39.png)

**Comment by Andrevdb** [comment]
@meomancer Can we change this to download the entire reporter_data table, filtered by the community that is being displayed?

For example, for Slocan, you could download all the records in reporter_data with Slocan as the community_id.

It would be nice for users to be able to download all the data in case they wanted to make custom graphs in Excel.

**Comment by meomancer** [comment]
hi @Andrevdb 
could you help me provide the latest dump database ? i don't  have some of column on my local database

**Comment by meomancer** [comment]
hi @Andrevdb 
could you check this ticket?

**Comment by meomancer** [comment]
I'm going to close this ticket
create new ticket for new review
