### ISSUE TITLE
Scheduled maintenance tickets

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#138]
![RecurringMaintenance](https://user-images.githubusercontent.com/178003/128737264-478ab047-05ce-4701-9958-17453a7828d1.png)

**Comment by timlinux** [comment]
Update wireframe based on workshopping round #2 with @meomancer 
![RecurringMaintenance](https://user-images.githubusercontent.com/178003/131475390-8422c806-1b93-4121-bf50-71d956f51e9e.png)

**Comment by Andrevdb** [comment]
@meomancer I might have broken something here when I was deleting the test tickets - we can't activate tickets at the moment. Is this something that we should demo at the presentation or should we wait?

**Comment by meomancer** [comment]
hi @Andrevdb 
this is fixed, could you check it?

**Comment by meomancer** [comment]
I'm going to close this ticket
create new ticket for new review
