### ISSUE TITLE
500 Error on invite user

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#140]
@meomancer Just in case you aren't aware of this:

![image](https://user-images.githubusercontent.com/40511773/128754783-aa462b0e-f935-43ac-b2fa-82e430967eb6.png)

Clicking **invite** leads to a 500 error.

**Comment by meomancer** [comment]
hi @Andrevdb 
This is temporary fixed for now
Because when invita user, mycivitas will send email, but we don't have smpt credential 
Please refer this ticket to solve this
https://github.com/landinfotech/civitas-asset-management/issues/141
