### ISSUE TITLE
Landing page experience

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#142]
Hi @Andrevdb 

Lindsay and I sat and thrashed out this concept for the landing page. Could you and Tjaart add your inputs?

The focus is on content and layout here, not on design, which we will address with Maria later. CC @meomancer 

![CMMSLandingPage](https://user-images.githubusercontent.com/178003/129576055-034c3e53-2b25-4fee-b211-dd4f0d0bf591.png)

**Comment by tjaartvdb** [comment]
Thoughts and suggestion: @meomancer @Andrevdb @timlinux @lkwalke4 
1. How does Civitas work - 2:  add note that user can user their own GIS technician
2. How does Civitas work - 3  No fees for this.  Risk calcs are done automatically provided the data is captured correctly 
3. How does Civitas work - 4 Add capital planning to this step?  @Andrevdb have completed this component and will demo to all shortly. 
4. Our story: Edit "LandInfo Technologies" 
5. User categories:  Can we help/guide potential users which user category will be suitable for them - say population less than 500 Silver, 500 - 2,000 gold and 2,000 plus diamond.  Also mention that user can start with silver it is easy to upgrade?

**Comment by Andrevdb** [comment]
@timlinux @meomancer @lkwalke4

Do you guys like the naming Silver, Gold, Diamond? Any thoughts on doing some Latin names for sizing? Minimus, medios, magna?

**Comment by Andrevdb** [comment]
This is a pretty old school page layout but the video has some really good content that I think would resonate well with our audience.

[](https://diamondmaps.com/)

**Comment by timlinux** [comment]
Thanks for the hints @Andrevdb and @tjaartvdb we will tweak as proposed.

**Comment by meomancer** [comment]
Landing page has been updated
please check it @tjaartvdb @Andrevdb @timlinux

**Comment by Andrevdb** [comment]
Hi @timlinux @lkwalke4 @meomancer @tjaartvdb 

Here's an updated concept (slowly moving toward design, thanks for your patience Irwan).

![Landing Page Design](https://user-images.githubusercontent.com/40511773/132255529-c752c701-3c80-4526-a4f2-0cfea6b4d3e2.png)

We are putting together some pictures for the background images. I'll also get together some pictures for the changing map picture for steps 2 to 5.

**Comment by tjaartvdb** [comment]
@Andrevdb @meomancer @lkwalke4 @timlinux
The edits from Andre is more in line with Three-step methodology (Inventory, Prioritize, Strategy) that LIT is using. Looks good.
Do we still need the  Carousel? I suggest we take it out for now.

**Comment by meomancer** [comment]
yes, we can take it @tjaartvdb 
i think the parallax is already enough to tells the story of website

I will start developing it tomorrow

**Comment by meomancer** [comment]
hi @Andrevdb @tjaartvdb  @lkwalke4 @timlinux

The landing page updated
Please check it

![Selection_137](https://user-images.githubusercontent.com/4530905/132325325-7be11ff7-9c3e-446c-bf72-9f3296ff03e7.png)

How does CIVITAS work is using parallax on scroll
![Selection_138](https://user-images.githubusercontent.com/4530905/132325337-c5c36868-e62d-4a42-9df1-98d023f995d1.png)
![Selection_139](https://user-images.githubusercontent.com/4530905/132325409-4299af5e-d962-40d3-bcaf-97b9ec0b451d.png)

Some of image is still in question mark, that i'm not sure the image of those
Could you help me prepare the image?


![Selection_140](https://user-images.githubusercontent.com/4530905/132325518-4bc50d0e-5556-42c8-9d9b-a9e4bd5f6177.png)


![Selection_141](https://user-images.githubusercontent.com/4530905/132325532-8673153c-5fbf-47f8-8c60-b23188b9aabb.png)


If there is comment, i will work on it tomorrow

**Comment by Andrevdb** [comment]
@meomancer This looks awesome!

I have a couple suggestions. The text is a bit difficult to read sometimes depending on monitor resolution. Here's a photo using this [darker version of the background image](https://drive.google.com/file/d/1DzH1peQ-Z0WSiLcl0pthWwzz2oXmET5p/view?usp=sharing), changing the text to white, and adding a black background around the text at 25% opacity.
![image](https://user-images.githubusercontent.com/40511773/132369927-fa4aad0a-5718-401c-8cbd-30c2bc3744cd.png)

A personal preference: Could we change "Welcome to MyCivitas.ca" -> "Welcome to MyCivitas" and CIVITAS to _Civitas_ for the entire landing page?

Could we change the theme colour blue to #1F497D, 
![image](https://user-images.githubusercontent.com/40511773/132375709-c6355ed0-8ca9-46dc-9188-84bced1da1cf.png)

Here are some suggestions for the parallax design:
![image](https://user-images.githubusercontent.com/40511773/132375848-e72248e0-ccd1-4d46-8fe3-e7da0ad18e28.png)

Here are some minor edits to the parallax content: 
Can we use the Village of Lumby, Water Network as an example for the maps? We have permission from them to show their data publicly. [Here is a picture](https://drive.google.com/file/d/1ciWC_IsHEGLd1DVzja_GMHFlZFHuHBEr/view?usp=sharing) to use for the capital planning step. [Here is a picture](https://drive.google.com/file/d/1obRKCjNWbb9-vaJHnbAWcL4fB5ie5Ooy/view?usp=sharing) to use for the We are Here to Help and Enjoy Asset Management steps
![Parallax Landing Page drawio](https://user-images.githubusercontent.com/40511773/132383228-32cbef2e-5b14-4166-9126-fa0a8b17ca9d.png)

And finally for the Our Story section of the landing page. Can we use [this picture](https://drive.google.com/file/d/18CEFSUX26ivxn6OqKktp4qyG40t5we7V/view?usp=sharing) as a background image and do a similar white text with a black transparent background?
![image](https://user-images.githubusercontent.com/40511773/132387936-0145c995-2ff1-4873-a86f-6cf0ecc59373.png)

I'll be up tonight if you want to email with any suggestions. Thanks!

**Comment by tjaartvdb** [comment]
@meomancer please update text for: We Are Here to Help
Let us know if you need any help along the way, from capturing data to presenting to council. We have a team of experienced staff available.
Please note that support is not included in the hosting fee. A popular option for small communities is to sign an annual support contract. Please inquire (support@civitas.ca) and we will connect you with a team member near you.

**Comment by Andrevdb** [comment]
Separate ticket for this ^

**Comment by meomancer** [comment]
can we close this ticket @Andrevdb @tjaartvdb @timlinux ?
