### ISSUE TITLE
Panel subtitle text

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#151]
This widget shows the features that are selected in map.

to 

This panel shows the features that are selected in map.

![image](https://user-images.githubusercontent.com/178003/131322765-ba3fc8e1-728a-4336-a5ae-d4f7cc929e12.png)

Maybe instead of 'Features' we should call them 'Assets' @Andrevdb ?

**Comment by meomancer** [comment]
This is fixed (deployed)

**Comment by timlinux** [comment]
LGTM thanks
