### ISSUE TITLE
Use currency in reports

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#156]
Can we put a currency symbol in front of numbers

![image](https://user-images.githubusercontent.com/178003/131324348-a3abea69-ecc2-4e7d-aaef-285dd9ad9c3b.png)

We should have a user option to set the currency for a community too...

TODO:
- [x] @Andrevdb put the currency column on database
- [ ] @meomancer get the new column and show it on frontend

**Comment by Andrevdb** [comment]
@timlinux  @meomancer Does it make sense for me to add this in to the view in the database?

**Comment by meomancer** [comment]
hi @Andrevdb 
i'm not sure, but user can't set any value on view, isn't it?
so i think we can put it on community database? (when community created, user will put the currency for their community)

**Comment by meomancer** [comment]
hi @Andrevdb @timlinux 
This ticket is fixed
But currently i put 'USD' as the currency

@Andrevdb 
Pleasse create new column "currency" in the community table
And put currency in there
Not the symbol, but the currency code (USD, CAD)

**Comment by Andrevdb** [comment]
![image](https://user-images.githubusercontent.com/40511773/132879502-11fad856-a5ed-450e-9f25-e3d0974372a1.png)
@meomancer A currency column is now added to the community table, I've added a currency code. Currently everyone is in CAD, maybe we'll have some Indonesian Rp sometime!

**Comment by meomancer** [comment]
hi @Andrevdb 
It is already implemented
The currency on frontend turns to CA$
Is that correct? (It is from library)

**Comment by Andrevdb** [comment]
Perfecto!
