### ISSUE TITLE
Increase Zoom Level

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#157]
@meomancer Can we increase the Zoom level of the web map? Water valves are sometimes close together and can be difficult to identify

**Comment by tjaartvdb** [comment]
@meomancer @timlinux @Andrevdb 
Will it be possible to increase the zoom level for the Oct release? It is difficult to select points close to each other:
![image](https://user-images.githubusercontent.com/71300724/135008702-274d1dfc-5244-4280-b11c-06efc41791d8.png)
![image](https://user-images.githubusercontent.com/71300724/135008843-974d3fd3-d877-4ff4-9627-b3ad977eacb4.png)

**Comment by tjaartvdb** [comment]
@meomancer - Zoom level good now!
