### ISSUE TITLE
Should be able to convert a ticket to a recurring ticket

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#160]
![image](https://user-images.githubusercontent.com/178003/131466163-3b86fd8c-a1a1-4e91-9299-48dabcfe1b41.png)

Currently if I edit a ticket there is no option to convert it to a scheduled task

**Comment by meomancer** [comment]
This has been fixed
Could you check it @timlinux ?

**Comment by timlinux** [comment]
I cant see any change on e.g. https://mycivitas.ca/work-order/tickets/54/ @meomancer

**Comment by meomancer** [comment]
it is "Public Ticket" @timlinux 

Just Scheduled Ticket that can make as recurring
![Selection_098](https://user-images.githubusercontent.com/4530905/131654993-d0359cca-b1cc-49c8-a0a2-e43e6b9b2473.png)

Or maybe we can also able to change the ticket type?

**Comment by meomancer** [comment]
I'm going to close this ticket
create new ticket for new review
