### ISSUE TITLE
Operator list should include all Managers, Operations Managers too....

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#166]
![image](https://user-images.githubusercontent.com/178003/131468318-ff6edb64-324b-4ed0-930a-5be7a2152a29.png)

I think we should be able to assign tickets to any level of user (manager, operations manager, operator). I am imagining a very small community where there is a single person subscribed to our platform and they basically take on all roles.

@Andrevdb thoughts?

**Comment by Andrevdb** [comment]
Hi @meomancer and @timlinux 

Yes, I agree that we should be able to assign this to all users in the organization regardless of level.

**Comment by meomancer** [comment]
This is updated, please check it @Andrevdb @timlinux

**Comment by meomancer** [comment]
I'm going to close this ticket
create new ticket for new review
