### ISSUE TITLE
Recurring tickets text

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#167]
![image](https://user-images.githubusercontent.com/178003/131469089-844427ad-ba4c-47fd-85f4-e45ea7baa10d.png)

When recurring is setup for this ticket, this ticket will automatically created for every recurring date

becomes:

A new ticket with the same details as this one will be created on each reocurrance.

Wording for recurrence behaviour:

Weekly every Monday
Monthly on day #1
Yearly on date 01 August

**Comment by meomancer** [comment]
This has been fixed
Could you check it @timlinux ?
