### ISSUE TITLE
500 Error when selecting ticket from Work Order page

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#168]
Logged in as admin and click on Work Orders:
![image](https://user-images.githubusercontent.com/40511773/131595405-b44b6655-ff90-4a04-a5a0-534c7f995ed1.png)

500 Error
![image](https://user-images.githubusercontent.com/40511773/131595458-fc813d8e-1b3b-4427-8a4a-25970d09fda8.png)

**Comment by meomancer** [comment]
This is fixed @Andrevdb 
please check it

**Comment by Andrevdb** [comment]
Thanks!
