### ISSUE TITLE
Error for point features on the ticket viewer

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#169]
![image](https://user-images.githubusercontent.com/40511773/131595824-12b6e7a1-f4ad-430e-bf39-f80c702c85ec.png)
For point features, I think the feature geometry is not working in the display

**Comment by meomancer** [comment]
This is fixed, could you check it @Andrevdb ?

**Comment by Andrevdb** [comment]
Perfect!
