### ISSUE TITLE
Organization/community  

### ISSUE THREAD

**Issue by tjaartvdb** [landinfotech/civitas-asset-management#170]
When editing an organization on the admin interface, the community is unintentionally changed because the assigned community is hidden from the dropdown list.  
Example: This organization (Port Hawkesbury) is assigned the community Port Hawkesbury but when edit organization is clicked, it is unable to keep the community the same. See image below - where community is set to Cormack

![image](https://user-images.githubusercontent.com/71300724/131600720-c1267e05-182a-4ffb-970f-0c288841f176.png)

**Comment by meomancer** [comment]
This is fixed, could you retry @tjaartvdb ?
