### ISSUE TITLE
Simpify user roles

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#177]
![image](https://user-images.githubusercontent.com/40511773/132106956-87856268-2b76-4573-b6bf-317ee2e59ef5.png)

We can simplify this I think.

- Admin (this is the first created user, has all rights to organization (add/remove/invite users, change subscription, create/delete/edit work order, view everything - this is the current manager
- Manager (create/delete/edit work order, view everything
- Operator (edit work orders, view everything)
- Viewer (view everything)

@timlinux  do you see any red flags here? @tjaartvdb

**Comment by Andrevdb** [comment]
In order of most to least privileged:
![image](https://user-images.githubusercontent.com/40511773/132262404-e06fd866-41b4-44a9-a18e-c71b26cf7e1a.png)
@meomancer  can you confirm that this change does not break any of your work with the work order system before I close it?

**Comment by meomancer** [comment]
It should not breaks anything @Andrevdb (i need to test it) 
But for administrator, when we create organisation, the user that create will be directly assign as Administrator?
And the one on only who will be administrator?

**Comment by Andrevdb** [comment]
@meomancer 
Yes, I think it would be good to automatically assign the first user to administrator because those privileges are needed set user roles or change subscription settings users. 

Sorry, I just made a change in the description:
![image](https://user-images.githubusercontent.com/40511773/132276552-0266cf07-5f71-4bc8-82b8-c1e36bb9e7a4.png)
We need at least one administrator per organization because someone has to be able to change the subscription options. Do you think makes sense?

**Comment by meomancer** [comment]
ok @Andrevdb 
i think it is already working fine
because it seems it is just renaming the role
we can set permissions in the user role detail

**Comment by Andrevdb** [comment]
@meomancer awesome thanks, I'm going to close this.
