### ISSUE TITLE
Add scroll bar to work order scheduler from template

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#178]
![image](https://user-images.githubusercontent.com/40511773/132107205-47e0c61a-30c3-4d69-a18f-360855fb0bbe.png)

On my resolution, I cannot see the bottom fields on the work order scheduler form. Can we add a scroll bar?

**Comment by Andrevdb** [comment]
Note that the scroll bar exists for the form that we use without template.

**Comment by meomancer** [comment]
This is fixed, can you try it @Andrevdb ?

**Comment by Andrevdb** [comment]
tyvm!
