### ISSUE TITLE
Add expected time to complete task

### ISSUE THREAD

**Issue by tjaartvdb** [landinfotech/civitas-asset-management#181]
Add a field for "Expected time to complete task (optional)".  Must be able to capture when the ticket is created and user must be able to edit 
![image](https://user-images.githubusercontent.com/71300724/132423451-c2e47370-1963-41fa-bd74-19b0a7bb023b.png)

**Comment by meomancer** [comment]
hi @tjaartvdb 
what is the different with due on?
so we can put help text to explain what they are

**Comment by tjaartvdb** [comment]
"Expected time to complete task" is the number of hours/minutes the operator is expected to spend to complete the task. This will be captured (optional) when the ticket is created (before the task is completed)
Note: This is different from the "Time spent (Optional)" that is captured by the operator once the task is completed.

**Comment by meomancer** [comment]
Hi @tjaartvdb 
This ticket has been fixed, please check it
