### ISSUE TITLE
Parallax text

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#186]
![image](https://user-images.githubusercontent.com/178003/132476454-b7f54240-bbd5-4ce3-bf3d-89b34ba23a4d.png)

        <div id="workflow-1" class="section">
            <div class="row">
                <div class="background" style="opacity: 1;">
                    <img src="/static/img/parallax/bg.5a2c56c2ecf6.svg">
                </div>
                <div class="col-8" style="filter: grayscale(100%);">
                    <div class="image" style="background: white">
                        <img src="/static/img/parallax/1.270d9025727f.png" style="opacity: 1;">
                    </div>
                </div>
                <div class="col-4 paragraph">
                    <div class="paragraph-wrapper" style="opacity: 0; top: -118.35px;">
                        <div class="paragraph-title">
                            How does Civitas work?
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="workflow-2" class="section">
            <div class="row">
                <div class="col-8">
                    <div class="image">
                        <img src="/static/img/parallax/2.e5b3e0b66ea0.png" style="opacity: 1;">
                    </div>
                </div>
                <div class="col-4 paragraph">
                    <div class="paragraph-wrapper" style="opacity: 0; top: -118.35px;">
                        <div class="paragraph-title">
                            Capture your infrastructure
                        </div>
                        <div class="paragraph-content">
                            Create an asset inventory using powerful mapping software. Our data capture system uses QGIS, a free and open source desktop application.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="workflow-3" class="section">
            <div class="row">
                <div class="col-8">
                    <div class="image">
                        <img src="/static/img/parallax/3.eab6cb6f95d5.png" style="opacity: 1;">
                    </div>
                </div>
                <div class="col-4 paragraph">
                    <div class="paragraph-wrapper" style="opacity: 0; top: -118.35px;">
                        <div class="paragraph-title">
                            Prioritize Your Assets
                        </div>
                        <div class="paragraph-content">
                            Our system performs risk assessment analysis and preventative maintenance planning analysis on your data.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="workflow-4" class="section">
            <div class="row">
                <div class="col-8">
                    <div class="image">
                        <img src="/static/img/parallax/4.5699e614302b.png" style="opacity: 1;">
                    </div>
                </div>
                <div class="col-4 paragraph">
                    <div class="paragraph-wrapper" style="opacity: 0; top: -118.35px;">
                        <div class="paragraph-title">
                            Support Your Capital Planning
                        </div>
                        <div class="paragraph-content">
                            Make informed decisions to support your capital planning.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="workflow-5" class="section">
            <div class="row">
                <div class="col-8">
                    <div class="image">
                        <img src="/static/img/parallax/5.498878faf5a6.png" style="opacity: 1;">
                    </div>
                </div>
                <div class="col-4 paragraph">
                    <div class="paragraph-wrapper" style="opacity: 0; top: -118.35px;">
                        <div class="paragraph-title">
                            Set Up Work Orders
                        </div>
                        <div class="paragraph-content">
                            Use the platform to plan ad hoc and scheduled maintenance planning tasks.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="workflow-6" class="section">
            <div class="row">
                <div class="col-8">
                    <div class="image">
                        <img src="/static/img/parallax/6.f05b06214ef4.png" style="opacity: 1;">
                    </div>
                </div>
                <div class="col-4 paragraph">
                    <div class="paragraph-wrapper" style="opacity: 0; top: -118.35px;">
                        <div class="paragraph-title">
                            We Are Here to Help
                        </div>
                        <div class="paragraph-content">
                            Let us know if you need any help along the way. We can provide a full service experience from capturing data to providing support.
                            We have a team of experienced staff available to help!
                            <br>
                            Please note that support is not included in the hosting fee. A popular option for small community is to sign up for an annual support contract.
                            Please inquire and we will connect you with an asset management professional near you (@civitas @landinfo @kartoza)
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="workflow-7" class="section">
            <div class="row">
                <div class="col-8">
                    <div class="image">
                        <img src="/static/img/parallax/6.f05b06214ef4.png" style="opacity: 1;">
                    </div>
                </div>
                <div class="col-4 paragraph">
                    <div class="paragraph-wrapper" style="opacity: 1; top: 216.675px;">
                        <div class="paragraph-title">
                            Enjoy Asset Management
                        </div>
                        <div class="paragraph-content">
                            Practice effective and sustainable asset management on our affordable platform to benefit of your community.
                        </div>
                    </div>
                </div>
            </div>
        </div>

**Comment by meomancer** [comment]
This fixed please check it @timlinux

**Comment by meomancer** [comment]
We can close this for now
