### ISSUE TITLE
Our story

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#187]
Please match the typography to the parallax entries

Our Story

MyCivitas was created by [LandInfo Technologies](https://www.landinfotech.com/) and [Kartoza](https://kartoza.com) after we identified a need for an affordable and easy to use asset management system for small communities. The large proprietary offerings are overly complex and far too expensive for most small communities to be able to invest time into or afford.
MyCivitas is Open Source software. This means that the intellectual property behind the platform is [freely available](https://github.com/landinfotech/civitas-asset-management) to everyone and developed by a community of users who care about solving the problems you deal with every day in your small community.

**Comment by timlinux** [comment]
Also make Open Source a second heading and put the OS block under it

**Comment by meomancer** [comment]
This fixed
