### ISSUE TITLE
Landing page images

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#188]
Hi @Andrevdb and @tjaartvdb 

Can we have another go at the landing page images? As you can see @meomancer has done a stunning job of making the landing page look awesome, but the I have some issues with the images:

1) They are the same images as on landinfortech.com - I would prefer that we give mycivitas its own identity
2) The second image, while beautiful, runs against the blue accent theme of the site. 

Could we find some inspirational small community images with lots of blue in them that we can use rather? Thanks!

**Comment by tjaart** [comment]
Hey there. I think you got the wrong Tjaart :) I have no idea what this is about.

**Comment by tjaartvdb** [comment]
Will do @timlinux

**Comment by timlinux** [comment]
> Hey there. I think you got the wrong Tjaart :) I have no idea what this is about.

Eish - so sorry about that!

**Comment by Andrevdb** [comment]
@timlinux Can you have a peek at [these images](https://drive.google.com/drive/folders/11Y2sPcjEXfKcPXMWh6wU79KbKSzZ5qlJ?usp=sharing)? The two by Erik McLean and the one named _Lunenburg_Street_ are pretty neat.

**Comment by tjaartvdb** [comment]
@timlinux @ @meomancer @lkwalke4 @Andrevdb 
Any preference or comments on the images for the Landing page?https://drive.google.com/drive/folders/11Y2sPcjEXfKcPXMWh6wU79KbKSzZ5qlJ?usp=sharing 
We need to pick two images (for the top and bottom of the page).

**Comment by Andrevdb** [comment]
@meomancer 

Can we replace the first photo behind Welcome to MyCivitas with the image named [**Revelstoke**](https://drive.google.com/file/d/1QGQM2Iq1xERLE_MAzJehHYLflDvSn8h3/view?usp=sharing)

and the final picture behind Our Story with the image named [**Charis and a Fire **Hydrant**]()**

**Comment by tjaartvdb** [comment]
> @meomancer
> 
> Can we replace the first photo behind Welcome to MyCivitas with the image named [**Revelstoke**](https://drive.google.com/file/d/1QGQM2Iq1xERLE_MAzJehHYLflDvSn8h3/view?usp=sharing)
> 
> and the final picture behind Our Story with the image named [**Chairs and a Fire **Hydrant**](https://drive.google.com/file/d/10i8Hu3apyyiSMt0aSuVNtdj4nYdxuUp1/view?usp=sharing)**

Sounds good! @meomancer

**Comment by meomancer** [comment]
this ticket is has child ticket
- [ ] Image for Set Up Work Order : https://github.com/landinfotech/civitas-asset-management/issues/190
- [ ] Enjoy asset management : https://github.com/landinfotech/civitas-asset-management/issues/191

**Comment by Andrevdb** [comment]
Hi @meomancer,

Can we remove the slide "Enjoy Asset Management" for now.

There is a picture for "We are here to help" [here](https://drive.google.com/file/d/1fI8arIbwkfvj6N5lUMorZpLk2vY_9_sX/view?usp=sharing)

**Comment by Andrevdb** [comment]
Closing this ticket -> opening this one https://github.com/landinfotech/civitas-asset-management/issues/245
