### ISSUE TITLE
We should use a nice example ticket rather than the timeline

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#190]
![image](https://user-images.githubusercontent.com/178003/132479793-22a4d881-a8e0-48c0-9d46-2dbad03003c9.png)

Could you make a 'real ticket' with nice details that we can rather show here instead of the timeline? @meomancer will then screenshot it and publish it

**Comment by meomancer** [comment]
Covered in https://github.com/landinfotech/civitas-asset-management/issues/188
