### ISSUE TITLE
Format cost fields

### ISSUE THREAD

**Issue by tjaartvdb** [landinfotech/civitas-asset-management#203]
Format cost fields to $ with comma as thousand separator – e.g. $ 74,522
![image](https://user-images.githubusercontent.com/71300724/132550022-ab0ed192-6b16-4515-b04b-e856113a9df2.png)
@meomancer

**Comment by meomancer** [comment]
This is fixed, please check my comment in this ticket
https://github.com/landinfotech/civitas-asset-management/issues/156
