### ISSUE TITLE
Minor text edits

### ISSUE THREAD

**Issue by tjaartvdb** [landinfotech/civitas-asset-management#204]
1. Edit text
Replace “Summary of the problem” with “Summary of issue or task”
Replace “Description of your issue” with “Description of issue or task”
![image](https://user-images.githubusercontent.com/71300724/132550715-ec9dfef3-e35c-43b2-a107-50c3881790c9.png)

2. Edit text
“Below is the asset(s) selected for the new ticket”
“Click here to show the asset(s) on the map”
![image](https://user-images.githubusercontent.com/71300724/132551245-0e7138be-a4c4-4f06-9db2-a6d912f0125b.png)

**Comment by meomancer** [comment]
This is fixed, please check it
