### ISSUE TITLE
Recurring ticket date 

### ISSUE THREAD

**Issue by tjaartvdb** [landinfotech/civitas-asset-management#205]
Change "today" to due date
![image](https://user-images.githubusercontent.com/71300724/132578237-0150ccb7-628b-40f4-a644-db006e5c7632.png)

**Comment by meomancer** [comment]
Hi @tjaartvdb 
CC @timlinux @Andrevdb 

Should we change it to "From Start Date" instead "Due Date"
It will create confusion because we have Start Date on the ticket

**Comment by tjaartvdb** [comment]
@meomancer  - Agreed,  change it to "From Start Date" instead "Due Date"

**Comment by meomancer** [comment]
This is updated
Could you check it @tjaartvdb @Andrevdb ?

**Comment by tjaartvdb** [comment]
@meomancer I get a "Server Error (500)" when submitting a ticket  - Please check

**Comment by meomancer** [comment]
hi @tjaartvdb 
i can't reproduce the error

Could you provide what user did you use? What project and asset and what are the values for the new ticket?
Thank you

**Comment by meomancer** [comment]
I'm going to close this ticket
create new ticket for new review
