### ISSUE TITLE
Error (500)

### ISSUE THREAD

**Issue by tjaartvdb** [landinfotech/civitas-asset-management#213]
hi @tjaartvdb 
i can't reproduce the error

Could you provide what user did you use? What project and asset and what are the values for the new ticket?
Thank you

_Originally posted by @meomancer in https://github.com/landinfotech/civitas-asset-management/issues/205#issuecomment-920535388_

**Comment by tjaartvdb** [comment]
@meomancer 
User: admin@kartoza.com  (same error if logged in as tvandenberg@landinfotech.com)
Project: Port Hawkesbury
Asset: error occurs on all assets tested
Example:
![image](https://user-images.githubusercontent.com/71300724/133643243-f0ee579b-22da-4790-977b-6b9655fb8a0e.png)
![image](https://user-images.githubusercontent.com/71300724/133643389-5a3e976b-f343-4f3f-8b68-247dee9beaa4.png)

When click on "Create Ticket"

![image](https://user-images.githubusercontent.com/71300724/133643624-5bc3bf1b-2c5e-4901-ab72-e2a888ff6a70.png)

**Comment by meomancer** [comment]
This is fixed, could you retry @tjaartvdb @Andrevdb ?
