### ISSUE TITLE
Add Province in community selection on signup

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#217]
@meomancer Can we add the Province Code to the community selection dropdown menu? Ex. Lumby, BC or something similar
![image](https://user-images.githubusercontent.com/40511773/133951446-be7e668e-c70c-469c-ab1e-227999584c5e.png)
We are going to run into issues of non-unique community names at some point.

**Comment by meomancer** [comment]
Hi @Andrevdb 
the community code has been added
Could you check it?

**Comment by Andrevdb** [comment]
Thank you! If we get lots more communities signed up, we may want to add a first dropdown Province before they select their community. The code is great for now!
