### ISSUE TITLE
Change in wording on Manage Access

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#218]
![image](https://user-images.githubusercontent.com/40511773/133954327-0394fcec-50fd-4d88-ac63-1bb020a382be.png)
Can we change the wording to "Your organization is using # of # available users. To increase or decrease the number of available users, please change your subscription."

**Comment by meomancer** [comment]
Can you check this @Andrevdb ?

**Comment by Andrevdb** [comment]
Thanks!
