### ISSUE TITLE
Unable to change Asset Type on scheduled work orders

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#219]
Hi @meomancer 
![image](https://user-images.githubusercontent.com/40511773/133955205-31244211-72e3-47cd-ac17-2f583d1731e4.png)

I can't seem to change the asset type when editing this. Can you check?

**Comment by meomancer** [comment]
This is fixed, can you check it @Andrevdb ?

**Comment by Andrevdb** [comment]
Perfecto thank yoou!
