### ISSUE TITLE
Change wording on Work Order Report & Statistic

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#220]
Hi @meomancer, 

another small spelling change: "Reports & Statistics". Thanks :)

![image](https://user-images.githubusercontent.com/40511773/133955315-5d08c7a1-1954-4287-baf8-03420bd3d064.png)

**Comment by meomancer** [comment]
This has been changed
Can you check it @Andrevdb ?

**Comment by Andrevdb** [comment]
Thank you!
