### ISSUE TITLE
Complete sending invitations and accept invitations

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#221]
Hi @meomancer,

It was nice to see you at the meeting today (tonight)! Is it possible to fix the send and accept invitation system before I send off the credentials to Jason to test the system?

![image](https://user-images.githubusercontent.com/40511773/134041028-2fcc20b0-68fd-4d92-9c5c-5787208d6b5c.png)

**Comment by meomancer** [comment]
hi @Andrevdb 
on last meeting, it said that the email system needs to be disabled to prevent spam while they are testing everything 
and we can't enabled email system just for invite user 

so i think we can do manually for now
After invitation, just copy the invitation url (click here)
![Selection_170](https://user-images.githubusercontent.com/4530905/134101476-0eb91028-f47c-45a2-b5af-04f75a442433.png)
![Selection_171](https://user-images.githubusercontent.com/4530905/134101482-f9fbfa95-a9d0-4ae4-ae32-2e3668af5e9a.png)

and give it to the others

**Comment by Andrevdb** [comment]
@meomancer Thank you
