### ISSUE TITLE
Edit ticket title

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#237]
Can managers edit ticket title?

**Comment by tjaartvdb** [comment]
- Managers must be able to edit the title (Summary of the issue) **and** Description of issue or task. 
- Users must be able to edit their own comments (and delete attached files) once posted.

**Comment by meomancer** [comment]
hi @tjaartvdb and @Andrevdb 
The site is updated
1. Can edit title. Just click "Edit" as usual and there will be Title of ticket as new form.
2. User who create and manager can edit and delete comment.
3. When click edit on a comment, we can delete the attactments

**Comment by tjaartvdb** [comment]
@meomancer Fixed!
