### ISSUE TITLE
Work Order Scheduler bug

### ISSUE THREAD

**Issue by tjaartvdb** [landinfotech/civitas-asset-management#242]
After deactivating WO in Work Order Scheduler, it still shows as a WO ticket when feature is selected
![image](https://user-images.githubusercontent.com/71300724/141506685-f216cb4d-441b-485c-b239-9f25ece01e82.png)
![image](https://user-images.githubusercontent.com/71300724/141507208-ea60a99b-1f09-49b4-bae2-18da9620592b.png)
@meomancer @Andrevdb @timlinux @lkwalke4

**Comment by meomancer** [comment]
hi @tjaartvdb 
the work order scheduler basically is just scheduling the ticket for recurring
when we inactive it, meaning that the ticket will note recreate in the next date, but the ticket is still open
so we need to close it manually in
https://mycivitas.ca/work-order/tickets/199/

do you need to autoclose the ticket when it turns to inactive?

**Comment by tjaartvdb** [comment]
thanks @meomancer Thjs makes sense. No need to auto close the ticket, it will work if we close it manually

**Comment by meomancer** [comment]
Could we close this ticket @tjaartvdb ?
