### ISSUE TITLE
#1 We need to fork helpdesk to landinfotech

### ISSUE THREAD

**Issue by meomancer** [landinfotech/civitas-asset-management#26]
hi @Andrevdb 
could you fork this repo using landinfotech account : https://github.com/django-helpdesk/django-helpdesk.git
so we can customize it based on our CMMS needs

child of #25

**Comment by Andrevdb** [comment]
Can you let me know if this worked? @meomancer

**Comment by meomancer** [comment]
It's working 
https://github.com/landinfotech/django-helpdesk
