### ISSUE TITLE
#7 Update Create ticket

### ISSUE THREAD

**Issue by meomancer** [landinfotech/civitas-asset-management#32]
child of #25

![Selection_150](https://user-images.githubusercontent.com/4530905/108336368-8adc5d80-7206-11eb-98be-81dc4dbe5c46.png)

- [x] Create ticket can just be accessed and created by Manager / Operator admins
- [x] We can remove Submitter Email Address
- [x] Change "Case Owner" to "Operator" 
@Andrevdb (i saw below), what is PM stand for?
![Selection_152](https://user-images.githubusercontent.com/4530905/108336531-b4958480-7206-11eb-828e-7185c91bd4b2.png)

- [x] Make "Case Owner"  required
- [x] I'm not sure what is queue in here, i think this is for categorizing the ticket. Maybe we can make it using System, or maybe we can update the category based on what the works for? (like : Repairing, Renewing, Ordering, etc) : CC @Andrevdb 
![Selection_151](https://user-images.githubusercontent.com/4530905/108336604-cecf6280-7206-11eb-9478-5d09add01e36.png)

**Comment by tjaartvdb** [comment]
PM = Preventative Maintenance Work Order.  
Initially we were only going to include PMs - but decided to do all types of Work Orders:
WO order type (drop down)
a.	Preventative Maintenance WO:
A preventive maintenance work order is a scheduled routine maintenance task performed on individual assets or groups of assets. Preventive maintenance keeps equipment in its existing state and prevents deterioration or failure. 
b.	Inspection WO:
An inspection work order includes inspection of an assets, reading of meters, etc.  Inspections are usually time-based. 
c.	Corrective maintenance WO
A corrective maintenance work order is unplanned. Usually identified during an inspection or when a complaint is received 
d.    General WO
A WO that is not Preventive, Inspection or Corrective
