### ISSUE TITLE
#8 Make timeline as default dashboard for operator

### ISSUE THREAD

**Issue by meomancer** [landinfotech/civitas-asset-management#33]
child of #25

- [ ] We need to make timeline dashboard as ddefault for operator
![Selection_153](https://user-images.githubusercontent.com/4530905/108337653-ee1abf80-7207-11eb-88ba-b8d853c7e502.png)

- [ ] We can change it to the widget like google calendar? what do you think @Andrevdb ?

**Comment by tjaartvdb** [comment]
I like the Google Calendar widget option @meomancer @Andrevdb

**Comment by Andrevdb** [comment]
Let's use the timeline widget as is for now.
