### ISSUE TITLE
#2 Create user role

### ISSUE THREAD

**Issue by meomancer** [landinfotech/civitas-asset-management#37]
child of #35

User role on organisation has:
- Owner : Can manage organisation
- Manager : Can assign user and user role to the organisation
- Operations Admin: Can create and see work order of the organisation
- Operator : Can just see his work order

hi @Andrevdb 
can you add/edit this section?

**Comment by tjaartvdb** [comment]
@meomancer @Andrevdb 
See doc on user roles and rights:[https://drive.google.com/file/d/1J53W0kxQ9UoHM-NQ3W_BMzhyPM93f__d/view?usp=sharing](url)
