### ISSUE TITLE
#3 Organisation subscribe system

### ISSUE THREAD

**Issue by meomancer** [landinfotech/civitas-asset-management#38]
child of https://github.com/landinfotech/civitas-asset-management/issues/35

Please confirm this @Andrevdb 

- Does operators admin can assign all of asset?
- if not, where is the restriction? is 1 organisation can use specific system? or specific community?

After this is decided:
- [x] Update organisation to be linked to what category of assets they allowed
- [x] Tickets can just be assigned to assets that allowed for that organisation

**Comment by tjaartvdb** [comment]
@meomancer Managers can assign WOs for all assets for a specific community(town). Not restricted by system

**Comment by meomancer** [comment]
Currently the organisation can just creating/assign/edit of their own assets that falls on their community
Manager, and Operations Admin can assign WO to anyone in their organisation
