### ISSUE TITLE
[EPIC] Subscription system

### ISSUE THREAD

**Issue by meomancer** [landinfotech/civitas-asset-management#39]
Please confirm this @Andrevdb 

Where the subscription implemented? is this in organisation?
For example:
- Is organisation can be allowed for x users for subscription x?
- Is organisation can be allowed for x system/community for subscription x?

**Comment by tjaartvdb** [comment]
@meomancer @Andrevdb - DRAFT subscription process for review:   
1.  An organization (town) decides to subscribe (this will provide access to all modules - Civitas AM, CMMS and future modules)
2. The person responsible for the Civitas subscription register on line. 
3. An admin user account is automatically created with subscription - with user name and password
4. The admin user logs into Civitas and selects number of users. 
    Options are:
   - Basic - 3 users  (say $50 CAD per year)
         - Admin: 1 user (created by default)
         - Users: 2 
              - This user account can be used for CMMS manager, CMMS  Operator, CMM viewer, Dashboard Viewer
              - The allocation of users right/role is managed by the admin user 
    - Intermediate - 5 users (say $90 CAD per year)
          - Admin 1
          - Users 4
     Advance - 10 users  (say $150 CAD per year)
          - Admin 1
          - Users 9
5. Once selected, payment is done via Stripe. 
6. An email is sent to each user to create/edit  user name and password
7. Subscription is valid for one year an needs to be renewed by admin user
Also see user roles: [https://drive.google.com/file/d/1J53W0kxQ9UoHM-NQ3W_BMzhyPM93f__d/view?usp=sharing](url)]
