### ISSUE TITLE
Add display_label to web_* layers and change styling for web map

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#53]
- [x] add display_label to web views @Andrevdb 
- [x] add labels and update styling in civitasgis_reader @Andrevdb 
- [x] add display label to technician civitasgis_technician @Andrevdb 
- [ ] allow zooming in farther before layer disappears in webmap @meomancer

**Comment by timlinux** [comment]
@Andrevdb are these things relating to the map? Ideally you can just manage them yourself  in QGIS - I can give you another session walkthrough to show you how. From Irwan's side, he should just need to know a list of layers to break the project out into. We can manage all the scale dependent hiding / showing features in the QGIS cartography rules.

**Comment by Andrevdb** [comment]
@timlinux Yes, they are all map styling related - and all the layer properties seem to be transferring perfectly onto the webmap except that regardless of the scale settings in QGIS, all the webmap layers disappear at around 1:2000-ish scale. Is there a global visible scale range setting that I'm missing?
