### ISSUE TITLE
Incorrect map request

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#54]
![image](https://user-images.githubusercontent.com/178003/116265455-0b718a00-a773-11eb-9388-e6d24bdd954a.png)

We should not be including getCapabilities in the map requests for tiles

**Comment by timlinux** [comment]
http://134.122.46.127:8080/map/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities?&service=WMS&request=GetMap&layers=Water%20Network&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=256&height=256&srs=EPSG%3A3857&bbox=-6828272.610771365,5719629.952523171,-6827966.862658225,5719935.70063631

Although the browser still seems to bring back the tile ok

**Comment by meomancer** [comment]
this is fixed @timlinux
