### ISSUE TITLE
Topological snapping issues

### ISSUE THREAD

**Issue by aperryGIS** [landinfotech/civitas-asset-management#64]
When snapping to vertex and segment is engaged for line items the newly created feature automatically snaps to the end of the last created vertex in the layer. I can't adjust the line segment with the vertex tool, even after saving and refreshing the layer and project.

**Comment by aperryGIS** [comment]
I can try! Maybe I can do a zoom recording?

Sent from my iPhone

On May 11, 2021, at 3:28 PM, Andre Van den Berg ***@***.***> wrote:

﻿

@aperryGIS<https://github.com/aperryGIS>
I ran into a similar problem where it would only snap lines to the end of an existing line. I'm trying to recreate this problem but am having troubles.. Are you able to take some screenshots and put them up here (including the settings on the snapping toolbar?) when it happens again?

**Comment by Andrevdb** [comment]
That sounds great!

**Comment by Andrevdb** [comment]
@aperryGIS not sure if this is still an issue, but have you tried to mess around with the topological editing button on the snapping toolbar? My oops was that I had it toggled on and lines would only snap to existing vertexes.
