### ISSUE TITLE
Allow more zooming in on web map 

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#69]
Can we adjust the maximum zoom to 1:250-ish scale?

See: [https://gis.stackexchange.com/questions/80866/qgis-wms-url-parameters-for-zoom-scale](url)
[https://docs.geoserver.org/stable/en/user/services/wms/reference.html#getmap](url)

**Comment by meomancer** [comment]
This is duplication of https://github.com/landinfotech/civitas-asset-management/issues/157
