### ISSUE TITLE
Error on GetFeature request

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#73]
This 400 error sometimes occurs. To reproduce:

1. Go to https://mycivitas.ca/
2. click on a community to zoom, and click on a feature
3. If GetFeatureInfo works, refresh page and repeat 1, 2. Occurring approximately 25% of the time.

jquery.min.js:2 GET https://mycivitas.ca/map/?SERVICE=WMS&REQUEST=GetFeatureInfo&BBOX=50.550301713392415%2C-119.14707455257535%2C50.55484168888132%2C-119.13700017551541&SRS=EPSG%3A4326&HEIGHT=666&WIDTH=939&QUERY_LAYERS=Natural%2CFleet%20and%20Equipment%2CStructures%2CTransportation%20Network%2CWater%20Network%2CWastewater%20Network%2CStormwater%20Network&INFO_FORMAT=application%2Fjson&i=390.25298144257033&j=305.0985791995757 400

**Comment by Andrevdb** [comment]
@meomancer 
![400 error](https://user-images.githubusercontent.com/40511773/120660698-70886180-c43c-11eb-83ea-b7a15f0cd162.png)

I'm still getting this 400 error, unfortunately. The highlighting of features is not working on the live website as well - maybe we have to publish your latest update still?

**Comment by meomancer** [comment]
Hi @Andrevdb 
Could you do hard refresh? I think your browser is using cache. It's already deployed on the server

**Comment by Andrevdb** [comment]
@meomancer 

Thanks! It is fixed and working beautifully!
