### ISSUE TITLE
Combine list of attributes under 

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#80]
- [ ] @Andrevdb  sketch up groups for feature attributes 
- [ ] @meomancer send to Irwan to integrate to list

![attribute_organizer](https://user-images.githubusercontent.com/40511773/121599933-9becec80-c9f8-11eb-85c1-f16c821e541a.png)

**Comment by meomancer** [comment]
Could you check is this ticket done @Andrevdb ?

**Comment by Andrevdb** [comment]
Thanks Irwan!
