### ISSUE TITLE
Create default graphs / reports 

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#81]
- [ ] create Excel dashboard with all graphs (referring to reporter data) @tjaartvdb 
- [ ] Decide where graphs will go (user interface) @tjaartvdb @Andrevdb 
- [ ] modify reporter_data view if needed @Andrevdb 
- [ ] send to Irwan to create in Django @meomancer

**Comment by Andrevdb** [comment]
@tjaartvdb 
Make these Metabase dashboard in relation to the views in #83

**Comment by meomancer** [comment]
hi @Andrevdb 
Is this ticket done?

**Comment by Andrevdb** [comment]
Hi @meomancer 
I still have to make some graphs. I'll do this next :)

**Comment by Andrevdb** [comment]
@tjaartvdb bump
