### ISSUE TITLE
Change name on dropdown views

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#83]
Detail View -> Work Orders
Inventory View -> Asset Register
Prioritization View -> Prioritization
Project View -> Projects

![view_names](https://user-images.githubusercontent.com/40511773/121601465-d8b9e300-c9fa-11eb-8797-7c7c04fd8d8f.png)

**Comment by meomancer** [comment]
Can you check this ticket @Andrevdb  ?
this updates already deployed on server

**Comment by Andrevdb** [comment]
Thanks Irwan!
