### ISSUE TITLE
Change CoF, PoF, Risk description /Styling

### ISSUE THREAD

**Issue by tjaartvdb** [landinfotech/civitas-asset-management#84]
**PoF:** 
1 =  Rare
2 = Unlikely
3 = Possible
4 = Likely 
5 = Almost Certain
**CoF**
1 = Minor
2 = Moderate
3 = Significant
4 = Major
5 = Catastrophic

**Comment by Andrevdb** [comment]
![image](https://user-images.githubusercontent.com/40511773/122160650-28e2dc00-ce25-11eb-8002-db4801d03b3b.png)
@tjaartvdb 

On the latest civitasgis_reader QGIS project there is pof, and cof with the new labels

**Comment by Andrevdb** [comment]
@tjaartvdb Can you let me know what you'd like for the Risk values and labels? I'll do that next

**Comment by tjaartvdb** [comment]
Risk Class Risk Score
Low High
None 1 2
Low 3 10
Med 11 15
High 16 20
Extreme 21 25

Tjaart Van den Berg
Principal
*Office* (902) 693 2137
*Cell* (250)  550 6468
***@***.***


www.landinfotech.com

**Comment by Andrevdb** [comment]
In addition to symbology, change the fields that are exposed via WMS for default, pof, cof, risk.

**Comment by Andrevdb** [comment]
Organize fields into categories that can be added into tabs on the toolbar in Civitas
