### ISSUE TITLE
Use QGIS Server to highlight selected objects

### ISSUE THREAD

**Issue by timlinux** [landinfotech/civitas-asset-management#87]
Not sustainable for long lists of features but I think for our use case we can do it and we get the advantage that selections will match the cartography of the original QGIS project. We can do this to resolve issues like this:

Pre selection

![image](https://user-images.githubusercontent.com/178003/122019689-f355d880-cdbb-11eb-9bf1-cc09ac263561.png)

Post selection

![image](https://user-images.githubusercontent.com/178003/122019789-108aa700-cdbc-11eb-88f5-5e603999bc72.png)

We can pass the FILTER and SELECTION parameters (bypassing mapproxy) to fetch as a whole scene WMS request.

```
https://mycivitas.ca/map/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=-117.810832341741019,50.23069460638875938,-117.7894681899521458,50.25286056048448557&CRS=CRS:84&WIDTH=826&HEIGHT=858&LAYERS=Water%20Hydrant&STYLES=&FORMAT=image/png&DPI=79&MAP_RESOLUTION=79&FORMAT_OPTIONS=dpi:79&TRANSPARENT=TRUE&FILTER=Water%20Hydrant:%22feature_id%22%20=%2013254%20OR%20%22feature_id%22%20=%2013250&SELECTION=Water%20Hydrant:13254,13250
```

**Comment by meomancer** [comment]
Can you check this ticket @timlinux ?
this updates already deployed on server

**Comment by Andrevdb** [comment]
@meomancer I noticed a little bug in the highlighting and also filtering layers. To recreate:

1. Only turn on a single layer (ex. water is visible) and select a feature. The feature does not highlight
![image](https://user-images.githubusercontent.com/40511773/122822076-79798f80-d292-11eb-8b7f-5d5b368124e8.png)
2. Then toggle the layer visibility (water is not visible), and the highlighting appears. Perhaps this is a render ordering issue?
![image](https://user-images.githubusercontent.com/40511773/122822215-a29a2000-d292-11eb-8b85-c4773a192c1f.png)

**Comment by meomancer** [comment]
ok @Andrevdb 
will fix it
