### ISSUE TITLE
Asset Management View

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#92]
this child of https://github.com/landinfotech/civitas-asset-management/issues/93

We need to standardize on some simple and pretty graphs that summarize these three areas of the asset management process. Ex, a donut chart showing breakdown of probability of failure by visible features

- [ ] Probability of Failure graphs 
- [ ] Consequence of Failure graphs
- [ ] Risk graphs

**Comment by Andrevdb** [comment]
The Donut Chart shows the total renewal cost by pof/cof/risk for all visible asset classes on the map
The horizontal bar graph shows the total renewal cost by pof/cof/risk for all visible asset classes on the map further grouped by asset sub_class. There may be a lot of these so perhaps a page slider could be included?

It would be nice to standardize on the colour ramp. This is what I've been using for the QGIS styling:

#d7191c for red
#fdae61 for orange
#ffff00 for yellow
#a6d96a for light green
#1a9641 for dark green

An example of the risk tab
![Asset_Management_Interface_Risk](https://user-images.githubusercontent.com/40511773/122847336-5532a880-d2bc-11eb-9fff-ca0cae5d2efb.png)

and the same template could be followed for the probability of failure and consequence of failure tabs with these assigned legends:
![image](https://user-images.githubusercontent.com/40511773/122847423-80b59300-d2bc-11eb-9665-50fc6f6cd818.png)
The layout of this legend could be made a little prettier I think :P

**Comment by meomancer** [comment]
Hi @Andrevdb 
what is the style for every features?
- Probability of Failure graphs
- Consequence of Failure graphs
- Risk graphs

So i think when user looking Probability of Failure graphs, the style will be changed, is that correct?
And could you provide the column for each of features? so we can generate the graph from it

**Comment by meomancer** [comment]
Hi @Andrevdb
what is the style for every features?

Probability of Failure graphs
Consequence of Failure graphs
Risk graphs
So i think when user looking Probability of Failure graphs, the style will be changed, is that correct?
And could you provide the column for each of features? so we can generate the graph from it

**Comment by Andrevdb** [comment]
Hi @meomancer,

When the risk tab is selected, the style should be set to 'risk'
When the probability of failure tab is selected, the style should be set to 'pof'
When the consequence of failure tab is selected the style should be set to 'cof'

![image](https://user-images.githubusercontent.com/40511773/123038448-470c8700-d3a5-11eb-9238-bb91470ae387.png)
Each layer in the civitasgis_reader project has a default, pof, cof, and risk styling. I believe that you can choose the style that is used through the GetMap request [QGIS Server Docs](https://docs.qgis.org/3.16/en/docs/training_manual/qgis_server/wms.html), but is probably a good idea to consult with the wizard @timlinux before you assume that I'm right, haha!
![image](https://user-images.githubusercontent.com/40511773/123038667-aec2d200-d3a5-11eb-81d8-a984f29e3e25.png)

Let me know what you think of this idea!

Cheers,
André

**Comment by Andrevdb** [comment]
@meomancer Here is a google sheet with a Pivot Table using demodata from a materialized view in Civitas Database named _reporter_data_. The reader user has been assigned SELECT permissions on this materialized view.

[Asset Management Graph Examples](https://docs.google.com/spreadsheets/d/1l9Ll8E9tiQlqQRvBGOWsRyv6cvJVVb32yDFmvYx2qe0/edit?usp=sharing)

**Comment by Andrevdb** [comment]
@meomancer I'll be up checking my email if you have any questions and try to get back to you as soon as possible :)

**Comment by meomancer** [comment]
hi @Andrevdb 
do you have anything in database that tells the colors for the class?
e.g: green for minor? Red for Catastrophic?

I'm going to make it managable in django admin first
We can drop it later if we want to be manageable in database level

**Comment by Andrevdb** [comment]
@meomancer I've added a column column to the pof, cof, and risk table showing the legend and colour. In the future we can use this when if we want to manage the colour in the database
