### ISSUE TITLE
Civitas Toolbar Layout Update

### ISSUE THREAD

**Issue by Andrevdb** [landinfotech/civitas-asset-management#93]
### Discussed in https://github.com/landinfotech/civitas-asset-management/discussions/91

<div type='discussions-op-text'>

<sup>Originally posted by **Andrevdb** June 21, 2021</sup>
Any thoughts on formalizing this user interface? @tjaartvdb @timlinux @meomancer

For our purposes, let's call the dropdown menu on the map 'Dashboard Themes'
There are three dashboard themes: Standard, Asset Management, and Work Orders.

**The Standard theme**
 is the default theme that is opened. It should include basic view and query operations. For now, maybe we can limit this to only the feature identification tab. I think it's inevitable that we'll be asked to include an address search with parcel and zoning layers because municipal staff are really looking for that functionality.
The WMS style parameter should be set to _default_ on the feature identification tab
![Standard_Interface](https://user-images.githubusercontent.com/40511773/122838342-bbaecb00-d2aa-11eb-81c1-7ab092b1480c.png)

**The Asset Management theme** 
should also include the feature identification tab. And also three additional tabs: Probability of Failure, Consequence of Failure, and Risk. Here is an issue for us to provide the graphs that we'd like in the toolbar #92 
![Asset_Management_Interface](https://user-images.githubusercontent.com/40511773/122846292-62e72e80-d2ba-11eb-88b0-2ba7aa05d142.png)

Same as with the Standard theme, the feature identification tab style = _default_
When the Probability of Failure tab is selected, can we set the the layer style from the WMS = _pof_
When the Consequence of Failure tab is selected, style = _cof_
Risk, style = _risk_
It would be nice to default to the Risk tab when the **Asset Management theme** is selected
</div>

**Comment by Andrevdb** [comment]
@timlinux could you fact check me to make sure changing the styling as per this WMS document is a possible thing? [QGIS Server Doc](https://docs.qgis.org/3.16/en/docs/training_manual/qgis_server/wms.html#ls-serving-wms)

**Comment by meomancer** [comment]
hi @Andrevdb 
So for Work Orders basically Ticket list?

How about create ticket? where should we put it?
is it should be for all of view can create ticket?
if yes, maybe we can move it to the the top/rigth, right of "admin", similiar with basket of e-commerce?

**Comment by meomancer** [comment]
hi @Andrevdb 
I think after i implement it? it seems we don't need this view?
![Selection_246](https://user-images.githubusercontent.com/4530905/123367272-e008f100-d5a3-11eb-9893-de3b02a89b7b.png)

Because the style is changed in thise section?
When we click tab, it will show the correct layer
![Selection_247](https://user-images.githubusercontent.com/4530905/123367333-f6af4800-d5a3-11eb-83ff-05cb55f874ee.png)

Though that this section is needed for changing the style, but it is changed on the tab level
![Selection_246](https://user-images.githubusercontent.com/4530905/123367272-e008f100-d5a3-11eb-9893-de3b02a89b7b.png)

I think we can remove it?

**Comment by meomancer** [comment]
Could you review this @Andrevdb @tjaartvdb?
Everything is already in staging

**Comment by Andrevdb** [comment]
@meomancer 
Fantastic, yes this looks great.

![image](https://user-images.githubusercontent.com/40511773/125960225-e5ad89f7-222f-4828-9e36-9b0c10a9a7a5.png)
Not sure if you are currently working on this,  but the styling is only working for the probability of failure and consequence of failure tabs.

**Comment by Andrevdb** [comment]
@meomancer apologies, it's only the _default_ styling that is not working. the P, C, and R tabs are working. Are you getting this issue as well?

**Comment by meomancer** [comment]
hi @Andrevdb 
it was a bug, please recheck it
i already fix it
