### ISSUE TITLE
inconsistency attribute name

### ISSUE THREAD

**Issue by meomancer** [landinfotech/civitas-asset-management#98]
**Problem**
Attribute name has some inconsistency on some features
Some features are using human string as the attribute name : Example : Feature ID
Some others are using code string as attribute name : Example : feature_id

Example:
https://mycivitas.ca/map/?SERVICE=WMS&REQUEST=GetFeatureInfo&BBOX=49.76263885142355%2C-117.48742818832399%2C49.76933310901521%2C-117.44766712188722&SRS=EPSG%3A4326&HEIGHT=483&WIDTH=1853&BUFFER=10&QUERY_LAYERS=Natural%2CFleet%20and%20Equipment%2CStructures%2CTransportation%20Network%2CWater%20Network%2CWastewater%20Network%2CStormwater%20Network&INFO_FORMAT=application%2Fjson&i=962&j=311

![Selection_298](https://user-images.githubusercontent.com/4530905/124218279-24f0d280-db24-11eb-846c-abb3068e68e5.png)

*Solution*
Currently our frontend is using code name format. Please decide which one should be used

**Comment by Andrevdb** [comment]
@meomancer I understand. My mistake. I'm going to change all the field names to human strings.

**Comment by Andrevdb** [comment]
![image](https://user-images.githubusercontent.com/40511773/124393211-34038c00-dcae-11eb-99ab-eaaa6f998492.png)
@meomancer Please see the Alias column to see the strings. I'll get this done in the next couple days!

**Comment by Andrevdb** [comment]
Complete Alias for all styles
- [ ] default 
- [ ] pof
- [ ] cof
- [ ] risk

**Comment by Andrevdb** [comment]
@meomancer Can you review to see if this is working for you now? I've added human strings to all the columns in QGIS.

A note on the **_equipment and fleet_** group is that they do not have any spatial component so there is only a style named _default_. Do we need cof, pof, and risk styles anyways?

And a note on the **_natural_** group also only have a _default_ style because these aren't included in any calculations at the moment. They do not have a probability of failure or risk values, or renewal cost.

**Comment by meomancer** [comment]
ok @Andrevdb 
i will update the code in my next LIT session

> A note on the equipment and fleet group is that they do not have any spatial component so there is only a style named default. Do we need cof, pof, and risk styles anyways?

> And a note on the natural group also only have a default style because these aren't included in any calculations at the moment. They do not have a probability of failure or risk values, or renewal cost.

Noted, i will update the code,
currently every layer will changes the style if we select cof, pof or risk

**Comment by meomancer** [comment]
This is fixed
